export const courses = [
  {
    CourseID: 19,
    Course: "Font del Llop",
    Par: "72",
    RankLeadingCourses: 7.8,
    Condition: 7.7,
    Area: "Alicante",
    Distance: 45,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 73,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/font-del-llop-golf-resort",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/10365_1585726039.613.jpg?v1",
  },
  {
    CourseID: 20,
    Course: "Alenda",
    Par: "72",
    RankLeadingCourses: 7.6,
    Condition: 7.8,
    Area: "Alicante",
    Distance: 45,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 72,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/alenda-golf",
    Booking: "https://open.imaster.golf/en/alenda/disponibilidad",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/595_1560416114.928.jpg?v1",
  },
  {
    CourseID: 21,
    Course: "El Plantio",
    Par: "72",
    RankLeadingCourses: 7.5,
    Condition: 7.8,
    Area: "Alicante",
    Distance: 45,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 55,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/club-de-golf-el-plant%C3%ADo",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/606_1670769346_791.jpg?v1",
  },
  {
    CourseID: 22,
    Par: "72",
    Course: "Alicante Golf",
    Par: "72",
    RankLeadingCourses: 7.4,
    Condition: 7.5,
    Area: "Alicante",
    Distance: 55,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 99,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/alicante-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/596_1660213595_181.jpg?v1",
  },
  {
    CourseID: 23,
    Course: "Club de Golf Bonalba",
    Par: "72",
    RankLeadingCourses: 7.3,
    Condition: 7.1,
    Area: "Alicante",
    Distance: 55,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 60,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/golf-bonalba",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/599_1525783033.152.jpg?v1",
  },
  {
    CourseID: 27,
    Course: "Altea Club de Golf",
    RankLeadingCourses: 7.8,
    Condition: 7.8,
    Area: "Benidorm",
    Distance: 75,
    Votes: 0,
    Par: 36,
    Holes: 9,
    Price: 42,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/altea-club-de-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/605_1616085556.731.jpg?v1",
  },
  {
    CourseID: 28,
    Course: "Melia Villaitana Championship",
    RankLeadingCourses: 7.8,
    Condition: 7.8,
    Area: "Benidorm",
    Distance: 75,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 115,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/melia-villaitana-golf-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/628_1397055635.279.jpg?v1",
  },
  {
    CourseID: 29,
    Course: "Puig Campana",
    RankLeadingCourses: 7.5,
    Condition: 7.6,
    Area: "Benidorm",
    Distance: 75,
    Votes: 0,
    Par: 36,
    Holes: 9,
    Price: 38,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/puig-campana-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/33179_1563009917.254.jpg?v1",
  },
  {
    CourseID: 18,
    Course: "La Manga South",
    RankLeadingCourses: 8.1,
    Condition: 8.1,
    Area: "Cartagena",
    Distance: 50,
    Votes: 0,
    Par: 73,
    Holes: 18,
    Price: 114,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/real-golf-la-manga-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/571_1448980430.998.jpg?v1",
  },
  {
    CourseID: 30,
    Course: "La Manga North",
    RankLeadingCourses: 7.6,
    Condition: 7.6,
    Area: "Cartagena",
    Distance: 50,
    Votes: 0,
    Par: 71,
    Holes: 18,
    Price: 114,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/real-golf-la-manga-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://lamangaclub.com/sites/default/files/styles/mobile_half_slide/public/2019-12/la-manga-club-golf-camponorte_0.jpg.webp?itok=G1ktS2Uh",
  },
  {
    CourseID: 31,
    Course: "La Manga West",
    RankLeadingCourses: 7.2,
    Condition: 7.2,
    Area: "Cartagena",
    Distance: 50,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 114,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/real-golf-la-manga-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://lamangaclub.com/sites/default/files/styles/mobile_half_slide/public/2019-12/la-manga-club-golf-campooeste1_1.jpg.webp?itok=tH-P9OjV",
  },
  {
    CourseID: 9,
    Course: "Roda",
    RankLeadingCourses: 7.9,
    Condition: 8.1,
    Area: "Lite söder",
    Distance: 35,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 75,
    Golfhäftet: "Nej",
    Comment: "Pensionärsbana, långsamt tempo",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/roda-golf-beach-resort",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/585_1512049651.jpg?v1",
  },
  {
    CourseID: 10,
    Course: "El Valle",
    RankLeadingCourses: 7.7,
    Condition: 7.7,
    Area: "Lite söder",
    Distance: 45,
    Votes: 0,
    Par: 71,
    Holes: 18,
    Price: 82,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/el-valle-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/8073_1526934298.93.jpg?v1",
  },
  {
    CourseID: 11,
    Course: "Hacienda Riquelme",
    RankLeadingCourses: 7.3,
    Condition: 6.7,
    Area: "Lite söder",
    Distance: 38,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 75,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/hacienda-riquelme-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/8108_1587324345.552.jpg?v1",
  },
  {
    CourseID: 12,
    Course: "La Torre",
    RankLeadingCourses: 7.2,
    Condition: 7,
    Area: "Lite söder",
    Distance: 40,
    Votes: 0,
    Par: 68,
    Holes: 18,
    Price: 79,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/la-torre-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/575_1525782963.134.jpg?v1",
  },
  {
    CourseID: 13,
    Course: "La Serena",
    RankLeadingCourses: 7.4,
    Condition: 7.5,
    Area: "Lite söder",
    Distance: 35,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 60,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/la-serena-golf-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/574_1585908657.398.jpg?v1",
  },
  {
    CourseID: 14,
    Course: "New Sierra",
    RankLeadingCourses: 7.1,
    Condition: 7.7,
    Area: "Lite söder",
    Distance: 45,
    Votes: 0,
    Par: 36,
    Holes: 9,
    Price: 23,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/new-sierra-golf-course",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/33005_1640160481_771.jpg?v1",
  },
  {
    CourseID: 15,
    Course: "Mar Menor",
    RankLeadingCourses: 7.1,
    Condition: 6.5,
    Area: "Lite söder",
    Distance: 40,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 62,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/mar-menor",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/583_1649431567_865.jpg?v1",
  },
  {
    CourseID: 16,
    Course: "Saurines",
    RankLeadingCourses: 7.4,
    Condition: 7.6,
    Area: "Lite söder",
    Distance: 40,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 59,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/saurines-de-la-torre",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/10724_1574696975.100.jpg?v1",
  },
  {
    CourseID: 17,
    Course: "Altoreal",
    RankLeadingCourses: 7.7,
    Condition: 7.5,
    Area: "Murcia",
    Distance: 60,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 60,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/club-de-golf-altorreal",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/568_1648494803_761.jpg?v1",
  },
  {
    CourseID: 24,
    Course: "Haciendo del Alamo",
    RankLeadingCourses: 7.7,
    Condition: 7.7,
    Area: "Murcia",
    Distance: 65,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 59,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/club-de-golf-hacienda-del-alamo",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/570_1463297184.113.jpg?v1",
  },
  {
    CourseID: 25,
    Course: "Alhama",
    RankLeadingCourses: 7.6,
    Condition: 7.1,
    Area: "Murcia",
    Distance: 80,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 60,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/alhama-signature",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/8066_1575472944.811.jpg?v1",
  },
  {
    CourseID: 26,
    Course: "Camposol",
    RankLeadingCourses: 6.9,
    Condition: 6.7,
    Area: "Murcia",
    Distance: 80,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 30,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/camposol-club-de-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/10730_1639245106_643.jpg?v1",
  },
  {
    CourseID: 1,
    Course: "Las Colinas",
    RankLeadingCourses: 8.6,
    Condition: 8.5,
    Area: "Torrevieja",
    Distance: 30,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 120,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/las-colinas-golf-country-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/10328_1415304449.015.jpg?v1",
  },
  {
    CourseID: 2,
    Course: "La Finca",
    RankLeadingCourses: 8.4,
    Condition: 8.5,
    Area: "Torrevieja",
    Distance: 25,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 110,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/la-finca-golf-la-finca-resort",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/620_1571404055.838.jpg?v1",
  },
  {
    CourseID: 3,
    Course: "Lo Romero",
    RankLeadingCourses: 8.4,
    Condition: 8.7,
    Area: "Torrevieja",
    Distance: 30,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 80,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/lo-romero-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/8123_1608107558.501.jpg?v1",
  },
  {
    CourseID: 4,
    Course: "Las Ramblas",
    RankLeadingCourses: 7.9,
    Condition: 8,
    Area: "Torrevieja",
    Distance: 25,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 73,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/las-ramblas-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/629_1389167441.009.jpg?v1",
  },
  {
    CourseID: 5,
    Course: "Vistabella",
    RankLeadingCourses: 7.7,
    Condition: 7.8,
    Area: "Torrevieja",
    Distance: 25,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 83,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/vistabella-golf",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/10818_1573659980.648.jpg?v1",
  },
  {
    CourseID: 6,
    Course: "Campoamor",
    RankLeadingCourses: 7.2,
    Condition: 6.6,
    Area: "Torrevieja",
    Distance: 25,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 79,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/real-club-de-golf-campoamor",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/627_1601722965.668.jpg?v1",
  },
  {
    CourseID: 7,
    Course: "Villamartin",
    RankLeadingCourses: 7.4,
    Condition: 7.4,
    Area: "Torrevieja",
    Distance: 20,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 75,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/villamartin-golf-la-finca-resort",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/598_1579341381.290.jpg?v1",
  },
  {
    CourseID: 8,
    Course: "La Marquesa",
    RankLeadingCourses: 7.3,
    Condition: 7.2,
    Area: "Torrevieja",
    Distance: 20,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 78,
    Golfhäftet: "Nej",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/golf-la-marquesa",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/610_1571401452.027.jpg?v1",
  },
  {
    CourseID: 32,
    Course: "Melia Villaitana Executive",
    RankLeadingCourses: 7.8,
    Condition: 7.8,
    Area: "Benidorm",
    Distance: 75,
    Votes: 0,
    Par: 62,
    Holes: 18,
    Price: 75,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+valencia/melia-villaitana-golf-club",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/628_1397055635.279.jpg?v1",
  },
  {
    CourseID: 33,
    Course: "Altoana Golf",
    RankLeadingCourses: 7.2,
    Condition: 7.1,
    Area: "Lite söder",
    Distance: 45,
    Votes: 0,
    Par: 72,
    Holes: 18,
    Price: 65,
    Golfhäftet: "Ja",
    Link: "https://www.leadingcourses.com/sv/clubs/europa+spanien+murcia/altaona-golf-country-village",
    Booking: "https://fontdelllop.golfmanager.com/consumer/ebookings?i=1",
    Image:
      "https://cdn.leadingcourses.com/userfiles/clubs/thumbs/fit-in/1920x1080/filters:format(webp)/filters:no_upscale()/33751_1674385182_500.jpg?v1",
  },
];
